language: ruby

matrix:
  include:
    - rvm: 2.6.3
    - rvm: 2.6.3
      env: RUBYOPT="--enable-frozen-string-literal  --debug=frozen-string-literal"
    - rvm: 2.7.1
    - rvm: 2.7.1
      env: RUBYOPT="--enable-frozen-string-literal  --debug=frozen-string-literal"
    - rvm: ruby-head
    - rvm: ruby-head
      env: RUBYOPT="--enable-frozen-string-literal  --debug=frozen-string-literal"
    - rvm: jruby-9.2.7.0
    - rvm: jruby-head
    - rvm: rbx-3
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
